### ISSUE TITLE
[help]轉檔過程中的錯誤訊息

### ISSUE THREAD

**Issue by leokjau** [caj2pdf/discussion#1]
嘗試對測試文件進行convert，個人使用的是caj2pdf-restructured，python是 3.9.5，mutool 是1.18.0

得到一連串訊息後被告知 "TypeError: argument of type 'WindowsPath' is not iterable"

本人不諳python，因為caj難用的情況，至使想轉成pdf，而努力嘗試caj2pdf，希望有大德高手可以幫忙教導如何修正此問題，謝謝

以下放上命令提示字元下的程序狀況

1. caj2pdf show a.caj (成功)
File: a.caj
Type: HN
Page count: 82
Outlines count: 44

2. caj2pdf convert a.caj -o a.pdf (失敗)
Traceback (most recent call last):
  File "c:\users\.......\python\python39\lib\runpy.py", line 197, in _run_module_as_main   return _run_code(code, main_globals, None,
  File "c:\users\......\python\python39\lib\runpy.py", line 87, in _run_code   exec(code, run_globals)
  File "C:\Users\......\Python\Python39\Scripts\caj2pdf.exe\__main__.py", line 7, in <module>
  File "c:\users\......\python\python39\lib\site-packages\caj2pdf\cli.py", line 54, in main    caj.convert(args.output)
  File "c:\users\......\python\python39\lib\site-packages\caj2pdf\cajparser.py", line 110, in convert    self._convert_hn(dest)
  File "c:\users\......\python\python39\lib\site-packages\caj2pdf\cajparser.py", line 339, in _convert_hn      from .dep.jbigdec import CImage
  File "c:\users\......\python\python39\lib\site-packages\caj2pdf\dep\jbigdec.py", line 26, in <module>   libjbigdec = cdll.LoadLibrary(pkg_dir / "bin/libjbigdec-w64.dll")
  File "c:\users\......\python\python39\lib\ctypes\__init__.py", line 452, in LoadLibrary   return self._dlltype(name)
  File "c:\users\.......\python\python39\lib\ctypes\__init__.py", line 364, in __init__     if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable

附轉檔文件，是個碩士論文
[a.zip](https://github.com/caj2pdf/discussion/files/6737435/a.zip)

感謝

**Comment by HinTak** [comment]
It seems to work fine here, this is the converted result:

[a.pdf](https://github.com/caj2pdf/discussion/files/6760057/a.pdf)

The problem seems to be whatever modification "caj2pdf-restructured" made, so you should contact them...

That said, it is `pkg_dir / "bin/libjbigdec-w64.dll"` and `if '/' in name or '\' in name` tell you the python interpreter does not like the "/" or "\" , and so dies. 'WindowsPath' is not iterable say the same.

```
cdll.LoadLibrary(pkg_dir / "bin/libjbigdec-w64.dll")
File "c:\users......\python\python39\lib\ctypes_init.py", line 452, in LoadLibrary return self.dlltype(name)
File "c:\users.......\python\python39\lib\ctypes_init.py", line 364, in init if '/' in name or '\' in name:
TypeError: argument of type 'WindowsPath' is not iterable
```

Please contact the author of "caj2pdf-restructured" .
